config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'
  devise_for :users
  resources :stores do
    resources :items
  end

  # AM: Interesting! I like how budget uses a combination of CRUD and custom routes.

  get "/budget", to: "budgets#show"
  get "/budget/check", to: "budgets#check"
  get "/about", to: "about#show"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :stores
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :stores
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
before_action :authenticate_user!

  def show
    @right_guess = []
    @total_spent = 0
    @guess_spent = 0
    @wrong_guess = []
    calculate_total_spent
  end

  # AM: You use a lot of business logic in your budgets controller. I think you would benefit from delegating a lot of this to a Budget model.
  # AM: It doesn't need to be an ActiveRecord model. It can have no connection to the database.

  # AM: Did not know `casecmp` was a thing!

  def check
    calculate_total_spent
    wrong_guess
    @user_input = budget_params["checker"]
    @right_guess = []
    @guess_spent = 0
    Store.all.each do |store|
      @user_input.each do |input|
        if store.name.casecmp(input) == input.casecmp(store.name)
          @right_guess.push(store.name)
          @guess_spent = @guess_spent + store.total_spent
        end
      end
    end
    @right_guess.each do |right|
      @wrong_guess.each do |wrong|
        if wrong.casecmp(right) == right.casecmp(wrong)
          @wrong_guess.delete(right)
        end
      end
    end

    render :show
  end

def wrong_guess
  @wrong_guess = []
    Store.all.each do |store|
      @wrong_guess.push(store.name)
    end
end

def calculate_total_spent
  @total_spent = 0
  @stores = Store.all
  @stores.each do |spent|
    @total_spent = @total_spent + spent.total_spent
  end
end

private
def budget_params
  params.permit(:checker => [])
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @store = Store.find(params[:store_id])
  end

  def new
    @store = Store.find(params[:store_id])
    @item = Item.new
  end

  def create
    @store = Store.find(params[:store_id])
    @item = @store.items.create(item_params)
    redirect_to store_path(@store)
  end

  def edit
    @item = Item.find(params[:id])
    @store = Store.find(params[:store_id])
  end

  def update
    @item = Item.find(params[:id])
    @store = Store.find(params[:store_id])
    @item.update(item_params)
    redirect_to store_path(@store)
  end

  def destroy
    @item = Item.find(params[:id])
    @store = Store.find(params[:store_id])
    @item.destroy
    redirect_to store_path(@store)
  end




private
  def item_params
    params.require(:item).permit(:name, :amount, :store_id)
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
# Will not update total_spent if individual store page isn't loaded
before_action :authenticate_user!, only: [:index, :create, :edit, :update, :destroy]

  # AM: Interesting approach to tallying up total spending!
  # AM: Do you think you could condense that functionality into a method so that it's in your Store model and not the view?

  def index
    @stores = Store.all
    @grandTotal = 0
  end
  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end
  def create
    @store = Store.create(store_params)
    redirect_to stores_path
  end

  def edit
      @store = Store.find(params[:id])
  end

  def update
      @store = Store.find(params[:id])
      @store.update(store_params)
      redirect_to store_path(@store)
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    redirect_to stores_path
  end


  private

  def store_params
    params.require(:store).permit(:name, :total_spent, :created_at)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/about/show.html.erb
<h1>Addicted to DEALS?!</h1>

<p>In our current marketplace any vulnerability to impulse spenting is being exploided heavily by big business. DEALS DEALS DEALS are everywhere, 70-80-90% off items if you buy NOW! It's very easy to get carried away with your spending if you are not careful. $10 here, $15 there, $20, all these expenses add up but they often go unnoticed because consumers are under the impression you saved $100s of dollars.</p>

<p>That's where "Where's my money" is here to help. "Where's my money" is an application that allows you to create a budget, then try to remember all the purchases you made. By becoming more aware of your impulse spending, and seeing the actual dollar amount that you don't remember spending, you will be able to make more conscience decisions when it comes to purchasing.</p> 

app/views/budgets/show.html.erb
<h1>Each box represents a store you shopped at</h1>

<h2>
Enter each store in the box (if you can't remember, submit anyway):
<form action="/budget/check" method="get">
    <% Store.all.each do %>
      <input type="text" name="checker[]" placeholder="Enter a store" />
    <% end %>
  <input id="budget_submit" type="submit" />
</form>
</h2>
<h3>So far you have spent: $<%= @total_spent %></h3>
  <div class="budget_guess">
    <h3>These are the stores you guessed right:</h3>
    <ul>
      <% @right_guess.each do |store| %>
        <li><%= store %></li>
      <% end %>
    <ul>
  </div>
  <div class="money_left">

<%# AM: Stay away from inline styling! Should keep CSS in your stylesheet. %>

<h3>So you know where <span style="color:green">$<%= @guess_spent %></span> is, but where is the other <span style="color:red">$<%= @total_spent - @guess_spent %></span>?</h3>
<h3>Forgot about these stores?</h3>
    <ul>
     <% @wrong_guess.each do |store| %>
        <li><%= store %></li>
      <% end %>
    </ul>
  </div>

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %> </h1>
<h2>
<%= form_for [@store, @item] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :amount %>
  $<%= f.text_field :amount %><br>

  <%= f.submit %>
<% end %>

<%= form_for [@store, @item], method: :delete do |f| %>
    <%= f.submit "Delete Item", class: "delete" %>
  <% end %>


</h2>

app/views/items/index.html.erb
This is the index

app/views/items/new.html.erb
<h1> Add New Item for <%= @store.name %> </h1>
<h2>
<%= form_for [@store, @item] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :amount %>
  $<%= f.text_field :amount %>


  <%= f.submit %>
<% end  %>
</h2>

app/views/items/show.html.erb
This is the show page

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WheresMyMoney</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav>
    <div class ="main_nav">
    <a href="/stores">Stores</a>
    <a href="/budget">Where's my money</a>
    <a href="/about">About</a>
  <% if current_user %>
    <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
  <% else %>
  <%= link_to 'Signup', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
  <% end %>
  </div>
  </nav>
<%= yield %>

</body>
</html>

app/views/stores/edit.html.erb
<h1> Edit "<%= @store.name %>" </h1>
<h2>
<%= form_for @store do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.submit %>
<% end  %>

<%= form_for(@store, method: :delete) do |f| %>
    <%= f.submit "Delete Store", class: "delete" %>
  <% end  %>
</h2>

app/views/stores/index.html.erb
<h1>Stores</h1>
<nav><%= link_to "Add Store", new_store_path %></nav>
<h3>
<ul>
  <% @stores.each do |store| %>
  <li><%= link_to store.name, store_path(store) %><br>
    Total: $<%= store.total_spent %> </li>
    <% @grandTotal = @grandTotal + store.total_spent %>
  <% end %>
  <p>Total Spent: $<%= @grandTotal %></p>
</ul>
</h3>

app/views/stores/new.html.erb
<h1> Add New Store </h1>
<h2>
<%= form_for(@store) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.hidden_field :total_spent, :value => 0 %>

  <%= f.submit %>
<% end  %>
</h2>

app/views/stores/show.html.erb
<nav><%= link_to "Edit Store", edit_store_path %></nav>
<h1> <%= @store.name %></h1>

<h3>
  <ul>
    <% @store.update(total_spent: 0) %>
    <% @store.items.each do |items| %>
      <li> <%= items.name %>: $<%= items.amount%> - <%= link_to "[edit]", "/stores/#{@store.id}/items/#{items.id}/edit" %> </li>
      <% @store.total_spent += items.amount %>
      <% @store.update(total_spent: @store.total_spent) %>
    <% end %>
    <%= link_to "Add Item", "/stores/#{@store.id}/items/new" %>
  </ul>
  <p>Total spent: $<%= @store.total_spent %> </p>